require('plugins.setup.nvim-tree')
require('plugins.setup.treesitter')
require('plugins.setup.telescope')
require('plugins.setup.fterm')
require('plugins.setup.specs')
require('plugins.setup.tabline')
require('plugins.setup.theme')
-- require('plugins.setup.mason')
-- require('plugins.setup.lsp')
require('plugins.setup.coc')
require('plugins.setup.which-key')
